//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public int acct_AccountID { get; set; }
        public string acct_Deleted { get; set; }
        public Nullable<int> acct_CreatedBy { get; set; }
        public Nullable<System.DateTime> acct_CreatedDate { get; set; }
        public Nullable<int> acct_UpdatedBy { get; set; }
        public Nullable<System.DateTime> acct_UpdatedDate { get; set; }
        public Nullable<int> acct_WorkflowID { get; set; }
        public Nullable<int> acct_WorkflowItemID { get; set; }
        public Nullable<int> acct_ZoneID { get; set; }
        public string acct_PhoneNumber { get; set; }
        public string acct_Email { get; set; }
        public string acct_IDCard { get; set; }
        public string acct_Company { get; set; }
        public string acct_BankAccount { get; set; }
        public string acct_Status { get; set; }
        public string acct_Name { get; set; }
        public Nullable<System.DateTime> acct_DOB { get; set; }
        public string acct_HouseNo { get; set; }
        public string acct_Street { get; set; }
        public string acct_Commune { get; set; }
        public string acct_District { get; set; }
        public string acct_Province { get; set; }
        public string acct_BankName { get; set; }
        public string acct_BackAccountName { get; set; }
        public Nullable<decimal> acct_Salary { get; set; }
        public string acct_Address { get; set; }
        public string acct_Remark1 { get; set; }
        public string acct_Remark2 { get; set; }
        public string acct_Remark3 { get; set; }
        public string acct_Verify1 { get; set; }
        public string acct_Verify2 { get; set; }
        public string acct_Verify3 { get; set; }
    }
}
