//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanRequest
    {
        public int loan_LoanRequestID { get; set; }
        public string loan_Deleted { get; set; }
        public Nullable<int> loan_CreatedBy { get; set; }
        public Nullable<System.DateTime> loan_CreatedDate { get; set; }
        public Nullable<int> loan_UpdatedBy { get; set; }
        public Nullable<System.DateTime> loan_UpdatedDate { get; set; }
        public Nullable<int> loan_WorkflowID { get; set; }
        public Nullable<int> loan_WorkflowItemID { get; set; }
        public Nullable<int> loan_ZoneID { get; set; }
        public Nullable<int> loan_AccountID { get; set; }
        public Nullable<decimal> loan_Amount { get; set; }
        public Nullable<int> loan_PayDay { get; set; }
        public Nullable<System.DateTime> loan_PayDate { get; set; }
        public Nullable<decimal> loan_LoanAmount { get; set; }
        public Nullable<decimal> loan_InterestRate { get; set; }
        public Nullable<decimal> loan_InterestAmount { get; set; }
        public string loan_Purpose { get; set; }
        public string loan_Status { get; set; }
        public string loan_RejectReason { get; set; }
        public string loan_Code { get; set; }
        public Nullable<decimal> loan_PaidAmount { get; set; }
        public Nullable<decimal> loan_Balance { get; set; }
    }
}
