//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPin
    {
        public int PinID { get; set; }
        public string pins_Deleted { get; set; }
        public Nullable<int> pins_CreatedBy { get; set; }
        public Nullable<System.DateTime> pins_CreatedDate { get; set; }
        public Nullable<int> pins_UpdatedBy { get; set; }
        public Nullable<System.DateTime> pins_UpdatedDate { get; set; }
        public Nullable<int> pins_WorkflowID { get; set; }
        public Nullable<int> pins_WorkflowItemID { get; set; }
        public Nullable<int> pins_ZoneID { get; set; }
        public string pins_Name { get; set; }
        public string pins_Status { get; set; }
        public Nullable<System.DateTime> pins_Date { get; set; }
        public Nullable<int> pins_AccountID { get; set; }
        public string pins_isUsed { get; set; }
        public string pins_Phone { get; set; }
    }
}
