//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanWebApp.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string aboutUs {
            get {
                return ResourceManager.GetString("aboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;About Us&lt;/h3&gt;&lt;hr /&gt;
        ///        &lt;p&gt;&lt;strong&gt;MARIELBank&lt;/strong&gt; began with a genuine desire to help the people of Cambodians who need quick cash to meet their daily needs.&lt;/p&gt;
        ///        
        ///        &lt;p&gt;&lt;strong&gt;MARIELBank&lt;/strong&gt; provides micro and small quick loans to the employed and the business owners.&lt;/p&gt;
        ///        
        ///        &lt;p&gt;We give you quick cash only and only if you need it, not you want it. So we want to see you use it wisely. We don&amp;rsquo;t bother to call you or we are not expected you to call us eit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string aboutUsContent {
            get {
                return ResourceManager.GetString("aboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul style=&quot;list-style-type:none;padding-left:0px&quot;&gt;
        ///                        &lt;li&gt;
        ///                            Building A Street 568 Sangkat
        ///                        &lt;/li&gt;
        ///                        &lt;li&gt;
        ///                            Beungkok II, Khan Toul kok, Phnom Penh, Cambodia
        ///                        &lt;/li&gt;
        ///                        &lt;li&gt;
        ///                            Phone: +855 67 69 69 67 or +855 70 69 69 67
        ///                        &lt;/li&gt;
        ///                        
        ///                        &lt;li&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already requested a loan!.
        /// </summary>
        public static string alreadyLoan {
            get {
                return ResourceManager.GetString("alreadyLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        public static string applyNow {
            get {
                return ResourceManager.GetString("applyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is already exist !.
        /// </summary>
        public static string emailExist {
            get {
                return ResourceManager.GetString("emailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string followUs {
            get {
                return ResourceManager.GetString("followUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string helpCenter {
            get {
                return ResourceManager.GetString("helpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Help Center&lt;/h3&gt;&lt;hr /&gt;
        ///        &lt;p class=&quot;Body&quot;&gt;&lt;strong&gt;Who we are ?&lt;/strong&gt;&lt;/p&gt;
        ///        &lt;p class=&quot;Body&quot;&gt;MARIELBank is born with a genuine desire to help people.&lt;/p&gt;
        ///        &lt;p class=&quot;Body&quot;&gt;We provide micro and small quick loans to the employed and the business owners.&lt;/p&gt;
        ///        &lt;p class=&quot;Body&quot;&gt;We give you quick cash only and only if you need it, not you want it. So we want to see you use it wisely. We don&amp;rsquo;t bother to call you or we are not expected you to call us either. Your privacy is our [rest of string was truncated]&quot;;.
        /// </summary>
        public static string helpCenterContent {
            get {
                return ResourceManager.GetString("helpCenterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number !.
        /// </summary>
        public static string invalidPhoneNumber {
            get {
                return ResourceManager.GetString("invalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN!.
        /// </summary>
        public static string invalidPin {
            get {
                return ResourceManager.GetString("invalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address.
        /// </summary>
        public static string ourAddress {
            get {
                return ResourceManager.GetString("ourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payback.
        /// </summary>
        public static string payback {
            get {
                return ResourceManager.GetString("payback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Payback Instruction&lt;/h3&gt;&lt;hr /&gt;
        ///        You can pay back by :&lt;br /&gt;&lt;br /&gt;
        ///        1- Wing Specialized Bank&lt;br/&gt; &lt;br /&gt;
        ///Account Number : 02394993 &lt;br /&gt;&lt;br /&gt;
        ///2- Acleda Bank&lt;br/&gt;&lt;br /&gt;
        ///        Account Name : Tep Chanrith &lt;br /&gt;&lt;br /&gt;
        ///        Account Number : 2200 00 559515 26 &lt;br /&gt;&lt;br /&gt;
        ///        By telling your &lt;strong&gt;loan number&lt;/strong&gt; and &lt;strong&gt;phone number&lt;/strong&gt;.&lt;br/&gt;&lt;br /&gt;
        ///        Then you will get email to confirm your payment..
        /// </summary>
        public static string paybackContent {
            get {
                return ResourceManager.GetString("paybackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is already exist !.
        /// </summary>
        public static string phoneExist {
            get {
                return ResourceManager.GetString("phoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Expired !.
        /// </summary>
        public static string pinExpired {
            get {
                return ResourceManager.GetString("pinExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please key in all required field(s)!.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait 30 more minutes to send sms again !.
        /// </summary>
        public static string wait30 {
            get {
                return ResourceManager.GetString("wait30", resourceCulture);
            }
        }
    }
}
