//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanWebApp.Resources.ui", typeof(ui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        public static string applyNow {
            get {
                return ResourceManager.GetString("applyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string bankAccount {
            get {
                return ResourceManager.GetString("bankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employement Letter.
        /// </summary>
        public static string empLetter {
            get {
                return ResourceManager.GetString("empLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get PIN.
        /// </summary>
        public static string getPIN {
            get {
                return ResourceManager.GetString("getPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have phone number ?.
        /// </summary>
        public static string hasPhonenumber {
            get {
                return ResourceManager.GetString("hasPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need.
        /// </summary>
        public static string I_need {
            get {
                return ResourceManager.GetString("I_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I pay in.
        /// </summary>
        public static string I_pay_in {
            get {
                return ResourceManager.GetString("I_pay_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string idCard {
            get {
                return ResourceManager.GetString("idCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Amount.
        /// </summary>
        public static string loan_Amount {
            get {
                return ResourceManager.GetString("loan_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request.
        /// </summary>
        public static string loanRequest {
            get {
                return ResourceManager.GetString("loanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL INFORMATION &amp; LOAN REQUEST.
        /// </summary>
        public static string personalinfo {
            get {
                return ResourceManager.GetString("personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment Amount.
        /// </summary>
        public static string Repayment_Amount {
            get {
                return ResourceManager.GetString("Repayment_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment Date.
        /// </summary>
        public static string Repayment_Date {
            get {
                return ResourceManager.GetString("Repayment_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PERSONAL INFORMATION.
        /// </summary>
        public static string reupload {
            get {
                return ResourceManager.GetString("reupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks. Your money will be transferred soon as below:.
        /// </summary>
        public static string thanks_success {
            get {
                return ResourceManager.GetString("thanks_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Number To Submit.
        /// </summary>
        public static string typeNumberToSubmit {
            get {
                return ResourceManager.GetString("typeNumberToSubmit", resourceCulture);
            }
        }
    }
}
